### ISSUE TITLE
Panic on unwrap in `ensure_imports`

### ISSUE THREAD

**Issue by johanhelsing** [bevyengine/naga_oil#55]
In my project, I'm getting the following panic:
```
thread 'Compute Task Pool (3)' panicked at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.1\src\compose\mod.rs:1356:59:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7/library\std\src\panicking.rs:617
   1: core::panicking::panic_fmt
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7/library\core\src\panicking.rs:117
   3: naga_oil::compose::Composer::ensure_import
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.1\src\compose\mod.rs:1336
   4: naga_oil::compose::Composer::ensure_imports<core::iter::adapters::map::Map<core::slice::iter::Iter<naga_oil::compose::ImportDefWithOffset>,naga_oil::compose::impl$8::make_naga_module::closure_env$5> >
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.1\src\compose\mod.rs:1365
   5: naga_oil::compose::Composer::make_naga_module
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.1\src\compose\mod.rs:1679
   6: bevy_render::render_resource::pipeline_cache::ShaderCache::get
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.0\src\render_resource\pipeline_cache.rs:320
   7: bevy_render::render_resource::pipeline_cache::PipelineCache::process_queue
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.0\src\render_resource\pipeline_cache.rs:793
   8: bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.0\src\render_resource\pipeline_cache.rs:825
   9: core::ops::function::FnMut::call_mut
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\core\src\ops\function.rs:166
  10: core::ops::function::impls::impl$3::call_mut
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\core\src\ops\function.rs:294
  11: bevy_ecs::system::function_system::impl$11::run::call_inner
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.0\src\system\function_system.rs:622
  12: bevy_ecs::system::function_system::impl$11::run
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.0\src\system\function_system.rs:625
  13: bevy_ecs::system::function_system::impl$6::run_unsafe<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>),void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::Pipel
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.0\src\system\function_system.rs:460
  14: core::panic::unwind_safe::impl$26::poll
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\core\src\panic\unwind_safe.rs:296
  15: futures_lite::future::impl$14::poll::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  16: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\core\src\panic\unwind_safe.rs:271
  17: futures_lite::future::impl$14::poll
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  18: async_executor::impl$5::spawn::async_block$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.1\src\lib.rs:145
  19: async_task::raw::RawTask<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::panic::unwind
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.4.0\src\raw.rs:563
  20: futures_lite::future::impl$12::poll
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:529
  21: async_executor::impl$5::run::async_fn$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_chan
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.1\src\lib.rs:243
  22: futures_lite::future::block_on::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
  23: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\thread\local.rs:270
  24: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\thread\local.rs:246
  25: futures_lite::future::block_on<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,enum2$<async_executor::impl$5::run::async_fn_env$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks:
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  26: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.0\src\task_pool.rs:171
  27: std::panicking::try::do_call
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\panicking.rs:524
  28: std::panicking::try
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\panicking.rs:488
  29: std::panic::catch_unwind
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\panic.rs:142
  30: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.0\src\task_pool.rs:165
  31: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\thread\local.rs:270
  32: std::thread::local::LocalKey<async_executor::LocalExecutor>::with
             at /rustc/180dffba142c47240ca0d93096ce90b9fd97c8d7\library\std\src\thread\local.rs:246
  33: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at C:\Users\Johan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.0\src\task_pool.rs:158
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
2023-09-09T08:41:57.642548Z ERROR matchbox_socket::webrtc_socket::socket: Socket(Io(Os { code: 10093, kind: Uncategorized, message: "Either the application has not called WSAStartup, or WSAStartup failed." }))
error: process didn't exit successfully: `target\debug\cargo_space.exe --dev --next 1 --no-ldtk --n 0` (exit code: 101)
```

I don't have a minimal test case, and it's entirely possible that I'm doing something weird or unsupported, but it kind of looks like the code is making incorrect assumptions. Would perhaps be better to make it an expect at least? And give the user some hint as to what they did wrong?

https://github.com/bevyengine/naga_oil/blob/b8bcd0344afa7dace11ce076337be49ed71dd9c2/src/compose/mod.rs#L1355

https://github.com/bevyengine/naga_oil/blob/b8bcd0344afa7dace11ce076337be49ed71dd9c2/src/compose/mod.rs#L1356

**Comment by johanhelsing** [comment]
One way to trigger it

```
git clone https://github.com/johanhelsing/bevy_smud
cd bevy_smud
cargo run --example time
```

**Comment by johanhelsing** [comment]
Upgrading form 0.8.1 to 0.8.2 solved it
